CREATE DATABASE IF NOT EXISTS ElectraTrace;
USE ElectraTrace;

DROP TABLE IF EXISTS LISTINGS;
DROP TABLE IF EXISTS VENDORS_IN;
DROP TABLE IF EXISTS FOOTPRINTS;
DROP TABLE IF EXISTS BOM_ITEM_LOGS;
DROP TABLE IF EXISTS BOM_ITEMS;
DROP TABLE IF EXISTS COMPONENTS;
DROP TABLE IF EXISTS BOM;
DROP TABLE IF EXISTS PROJECTS;

CREATE TABLE PROJECTS (
    Proj_ID INT AUTO_INCREMENT PRIMARY KEY,
    Project_Name VARCHAR(255) NOT NULL,
    Creation_Date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    Description TEXT,
    Total_Est_Budget DECIMAL(10, 2),
    Lead_Name VARCHAR(100),
    Due_Date DATE,
    Version_Tag VARCHAR(20),
    Status VARCHAR(50) DEFAULT 'Active'
);

CREATE TABLE BOM (
    BOM_ID INT AUTO_INCREMENT PRIMARY KEY,
    Proj_ID INT NOT NULL,
    BOM_Name VARCHAR(255) NOT NULL,
    FOREIGN KEY (Proj_ID) REFERENCES PROJECTS(Proj_ID) ON DELETE CASCADE
);

CREATE TABLE COMPONENTS (
    Comp_ID INT AUTO_INCREMENT PRIMARY KEY,
    MPN VARCHAR(100) NOT NULL UNIQUE,
    Description TEXT,
    Category VARCHAR(100),
    Datasheet_URL VARCHAR(500)
);

CREATE TABLE BOM_ITEMS (
    BOM_ItemID INT AUTO_INCREMENT PRIMARY KEY,
    BOM_ID INT NOT NULL,
    Comp_ID INT NOT NULL,
    parent_BOM_ItemID INT NULL,
    Quantity_Required INT NOT NULL DEFAULT 1,
    Status ENUM('Pending', 'Ordered', 'In Stock', 'Assembled') DEFAULT 'Pending',
    FOREIGN KEY (BOM_ID) REFERENCES BOM(BOM_ID) ON DELETE CASCADE,
    FOREIGN KEY (Comp_ID) REFERENCES COMPONENTS(Comp_ID) ON DELETE RESTRICT,
    FOREIGN KEY (parent_BOM_ItemID) REFERENCES BOM_ITEMS(BOM_ItemID) ON DELETE CASCADE
);

CREATE TABLE BOM_ITEM_LOGS (
    Log_ID INT AUTO_INCREMENT PRIMARY KEY,
    BOM_ItemID INT NOT NULL,
    Old_Status VARCHAR(50),
    New_Status VARCHAR(50),
    Changed_At TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (BOM_ItemID) REFERENCES BOM_ITEMS(BOM_ItemID) ON DELETE CASCADE
);

CREATE TABLE FOOTPRINTS (
    FP_ID INT AUTO_INCREMENT PRIMARY KEY,
    Comp_ID INT NOT NULL,
    Package_Type VARCHAR(100),
    Footprint_Name VARCHAR(100),
    CAD_Link VARCHAR(500),
    Model_3D_Link VARCHAR(500),
    FOREIGN KEY (Comp_ID) REFERENCES COMPONENTS(Comp_ID) ON DELETE CASCADE
);

CREATE TABLE VENDORS_IN (
    Vendor_ID INT AUTO_INCREMENT PRIMARY KEY,
    Vendor_Name VARCHAR(255) NOT NULL,
    Location_City VARCHAR(100),
    GSTIN VARCHAR(15),
    Contact_Info VARCHAR(255),
    Website VARCHAR(255)
);

CREATE TABLE LISTINGS (
    Listing_ID INT AUTO_INCREMENT PRIMARY KEY,
    Comp_ID INT NOT NULL,
    Vendor_ID INT NOT NULL,
    Price_INR DECIMAL(10, 2) NOT NULL,
    Stock_Qty INT NOT NULL DEFAULT 0,
    Purchase_URL VARCHAR(500),
    Last_Updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (Comp_ID) REFERENCES COMPONENTS(Comp_ID) ON DELETE CASCADE,
    FOREIGN KEY (Vendor_ID) REFERENCES VENDORS_IN(Vendor_ID) ON DELETE CASCADE
);

-- Creating a View
CREATE OR REPLACE VIEW available_stock_view AS
SELECT 
    l.Listing_ID,
    c.Comp_ID,
    c.MPN,
    c.Description AS Component_Desc,
    c.Category,
    v.Vendor_ID,
    v.Vendor_Name,
    v.Location_City,
    l.Price_INR,
    l.Stock_Qty,
    l.Purchase_URL,
    l.Last_Updated
FROM LISTINGS l
JOIN COMPONENTS c ON l.Comp_ID = c.Comp_ID
JOIN VENDORS_IN v ON l.Vendor_ID = v.Vendor_ID;

-- Creating a Stored Procedure
DROP PROCEDURE IF EXISTS GetFullBOMDetails;
CREATE PROCEDURE GetFullBOMDetails (IN p_BOM_ID INT)
SELECT 
    bi.BOM_ItemID,
    bi.parent_BOM_ItemID,
    c.MPN,
    c.Description,
    c.Category,
    bi.Quantity_Required,
    bi.Status
FROM BOM_ITEMS bi
JOIN COMPONENTS c ON bi.Comp_ID = c.Comp_ID
WHERE bi.BOM_ID = p_BOM_ID
ORDER BY bi.parent_BOM_ItemID, bi.BOM_ItemID;

-- Creating a Trigger
DROP TRIGGER IF EXISTS LogBOMItemStatusUpdate;
CREATE TRIGGER LogBOMItemStatusUpdate
AFTER UPDATE ON BOM_ITEMS
FOR EACH ROW
INSERT INTO BOM_ITEM_LOGS (BOM_ItemID, Old_Status, New_Status)
SELECT NEW.BOM_ItemID, OLD.Status, NEW.Status
WHERE OLD.Status <> NEW.Status;
